app_c#/PetApp/Models/Dog.cs
using System.ComponentModel.DataAnnotations;

namespace PetApp.Models;

public class Dog
{
    [Required(ErrorMessage = "The dog's name is required.")]
    public string? DogName { get; set; }
    public string? Owner { get; set; }
    public string? Address { get; set; }
    public string? OwnerPhoneNumber { get; set; }
    public DateTime DateOfBirth { get; set; } = new DateTime(2000, 1, 1);
    public int ConvertedAgeInDays { get; set; }
    public int ConvertedAgeInYears { get; set; }
}

app_c#/PetApp/Models/ErrorViewModel.cs
namespace PetApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

app_c#/PetApp/Models/Healthcheck.cs
using Microsoft.Extensions.Diagnostics.HealthChecks;

namespace PetApp.Models;

public class Healthcheck : IHealthCheck
{
    public Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context,
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult(HealthCheckResult.Healthy());
    }
}

app_c#/PetApp/Controllers/DogController.cs
using Microsoft.AspNetCore.Mvc;
using PetApp.Converters;
using PetApp.Models;
using Prometheus;
using static System.Int32;

namespace PetApp.Controllers;

public class DogController : Controller
{
    private readonly Counter _convertAgeCalls
        = Metrics.CreateCounter("convert_age_calls", "Number of calls of ConvertAge route");

    private readonly string _visitsPath = $"{Directory.GetCurrentDirectory()}/volume/visits";

    public IActionResult Index()
    {
        UpdateVisits();
        return View();
    }

    [HttpPost]
    public IActionResult ConvertAge(Dog model)
    {
        _convertAgeCalls.Inc();

        if (!ModelState.IsValid)
        {
            return View("Index", model);
        }

        model.ConvertedAgeInDays = AgeConverter.FromDateInDays(model.DateOfBirth);
        model.ConvertedAgeInYears = AgeConverter.DaysToYears(model.ConvertedAgeInDays);

        return View("Profile", model);
    }

    [Route("visits")]
    [HttpGet]
    public async Task<IActionResult> Visits()
    {
        var value = await ReadVisits();
        return new ObjectResult(value);
    }

    private async Task<string> ReadVisits()
    {
        return await System.IO.File.ReadAllTextAsync(_visitsPath);
    }

    private void UpdateVisits()
    {
        Console.WriteLine(_visitsPath);

        var value = System.IO.File.ReadAllText(_visitsPath);
        TryParse(value, out var number);
        System.IO.File.WriteAllTextAsync(_visitsPath, (number + 1).ToString());
    }
}

app_c#/PetApp/Views/Dog/Index.cshtml
@model Dog

<div style="text-align: center;">
    <h2>Dog Profile</h2>
</div>

<div class="form-container">
    <form method="post" asp-action="ConvertAge">
        <div class="form-group">
            <label>Dog Name:</label>
            <input asp-for="DogName" class="form-control"/>
            <span asp-validation-for="DogName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Date of Birth:</label>
            <input asp-for="DateOfBirth" type="date" class="form-control" value="2000-01-01"/>
        </div>
        <div class="form-group">
            <label>Owner:</label>
            <input asp-for="Owner" class="form-control"/>
        </div>
        <div class="form-group">
            <label>Address:</label>
            <input asp-for="Address" class="form-control"/>
        </div>
        <div class="form-group">
            <label>Owner Phone Number:</label>
            <input asp-for="OwnerPhoneNumber" class="form-control"/>
        </div>

        <div class="dog-form-submit-button">
            <button type="submit" class="btn btn-primary">Convert Age</button>
        </div>
    </form>
</div>

@if (Model is {ConvertedAgeInDays: > 0 })
{
    <div>
        <p>Converted Age: @Model.ConvertedAgeInDays</p>
    </div>
}

app_c#/PetApp/Views/Dog/Profile.cshtml
@model Dog

<h2>Dog Profile</h2>

<div>
    <p>
        <strong>Dog Name:</strong> @Model.DogName
    </p>
    <p>
        <strong>Date of birth:</strong> @Model.DateOfBirth.ToString("dd.MM.yyyy")
    </p>
    <p>
        <strong>Owner:</strong> @Model.Owner
    </p>
    <p>
        <strong>Address:</strong> @Model.Address
    </p>
    <p>
        <strong>Owner Phone Number:</strong> @Model.OwnerPhoneNumber
    </p>
    <p>
        <strong>Converted Age [Days]:</strong> @Model.ConvertedAgeInDays
    </p>
    <p>
        <strong>Converted Age [Years]:</strong> @Model.ConvertedAgeInYears
    </p>
</div>

app_c#/PetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PetApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Dog" asp-action="Index">PetApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - PetApp
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>